---
Name: pageicons
---

SilverStripe\CMS\Model\SiteTree:
  icon: 'innoweb/silverstripe-page-icons: client/icons/page.svg'
  icon_class: false

Page:
  icon: 'innoweb/silverstripe-page-icons: client/icons/page.svg'

SilverStripe\ErrorPage\ErrorPage:
  icon: 'innoweb/silverstripe-page-icons: client/icons/error.svg'
  icon_class: false

SilverStripe\CMS\Model\RedirectorPage:
  icon: 'innoweb/silverstripe-page-icons: client/icons/redirect.svg'
  icon_class: false

SilverStripe\CMS\Model\VirtualPage:
  icon: 'innoweb/silverstripe-page-icons: client/icons/virtual.svg'
  icon_class: false

---
Name: pageicons-userforms
Only:
  moduleexists: 'silverstripe/userforms'
---
SilverStripe\UserForms\Model\UserDefinedForm:
  icon: 'innoweb/silverstripe-page-icons: client/icons/form.svg'
  icon_class: false

---
Name: pageicons-blog
Only:
  moduleexists: 'silverstripe/blog'
---
SilverStripe\Blog\Model\Blog:
  icon: 'innoweb/silverstripe-page-icons: client/icons/blog.svg'
  icon_class: false

---
Name: pageicons-multisites
Only:
  moduleexists: 'symbiote/silverstripe-multisites'
---
Symbiote\Multisites\Model\Site:
  icon: 'innoweb/silverstripe-page-icons: client/icons/website.svg'
  icon_class: false
